### ISSUE TITLE
Update the profile with an avatar raises an error 

### ISSUE THREAD

**Issue by cnouguier** [kalisio/aktnmap#133]
The error is raised when navigating back to the profile:

vendor.b1f54f19.js:223440 Forbidden {type: "FeathersError", name: "Forbidden", message: "You are not allowed to perform create operation on storage", code: 403, className: "forbidden", …}
log @ vendor.b1f54f19.js:223440
(anonymous) @ vendor.b1f54f19.js:189268
Promise.then (async)
(anonymous) @ vendor.b1f54f19.js:189267
processHooks @ vendor.b1f54f19.js:189253
(anonymous) @ vendor.b1f54f19.js:190140
Promise.catch (async)
(anonymous) @ vendor.b1f54f19.js:190130
mixin.<computed> @ vendor.b1f54f19.js:190202
newMethod @ vendor.b1f54f19.js:190331
onThumbnailGenerated @ 46f15d26.84a4cf1a.js:236
invokeWithErrorHandling @ vendor.b1f54f19.js:77064
invoker @ vendor.b1f54f19.js:77287
invokeWithErrorHandling @ vendor.b1f54f19.js:77064
Vue.$emit @ vendor.b1f54f19.js:78893
(anonymous) @ 46f15d26.84a4cf1a.js:13
value @ 46f15d26.84a4cf1a.js:13
_callee2$ @ 46f15d26.84a4cf1a.js:470
tryCatch @ vendor.b1f54f19.js:204750
invoke @ vendor.b1f54f19.js:204979
prototype.<computed> @ vendor.b1f54f19.js:204802
asyncGeneratorStep @ vendor.b1f54f19.js:288207
_next @ vendor.b1f54f19.js:288229
Promise.then (async)
asyncGeneratorStep @ vendor.b1f54f19.js:288217
_next @ vendor.b1f54f19.js:288229
(anonymous) @ vendor.b1f54f19.js:288236
F @ vendor.b1f54f19.js:157106
(anonymous) @ vendor.b1f54f19.js:288225
(anonymous) @ 46f15d26.84a4cf1a.js:481
_callee3$ @ 46f15d26.84a4cf1a.js:445
tryCatch @ vendor.b1f54f19.js:204750
invoke @ vendor.b1f54f19.js:204979
prototype.<computed> @ vendor.b1f54f19.js:204802
asyncGeneratorStep @ vendor.b1f54f19.js:288207
_next @ vendor.b1f54f19.js:288229
(anonymous) @ vendor.b1f54f19.js:288236
F @ vendor.b1f54f19.js:157106
(anonymous) @ vendor.b1f54f19.js:288225
initialize @ 46f15d26.84a4cf1a.js:498
fill @ 2fef39b4.46113949.js:162
(anonymous) @ 37cf796c.a8164e79.js:1014
fill @ 37cf796c.a8164e79.js:1012
(anonymous) @ vendor.b1f54f19.js:115781
fillEditor @ vendor.b1f54f19.js:115776
(anonymous) @ vendor.b1f54f19.js:115978
step @ vendor.b1f54f19.js:115713
(anonymous) @ vendor.b1f54f19.js:115713
Promise.then (async)
step @ vendor.b1f54f19.js:115713
(anonymous) @ vendor.b1f54f19.js:115713
Promise.then (async)
step @ vendor.b1f54f19.js:115713
(anonymous) @ vendor.b1f54f19.js:115713
Promise.then (async)
step @ vendor.b1f54f19.js:115713
(anonymous) @ vendor.b1f54f19.js:115713
(anonymous) @ vendor.b1f54f19.js:115713
refresh @ vendor.b1f54f19.js:115980
created @ 731e11f8.95203d26.js:66
invokeWithErrorHandling @ vendor.b1f54f19.js:77064
callHook @ vendor.b1f54f19.js:79187
Vue._init @ vendor.b1f54f19.js:79862
VueComponent @ vendor.b1f54f19.js:79999
createComponentInstanceForVnode @ vendor.b1f54f19.js:78341
init @ vendor.b1f54f19.js:78174
createComponent @ vendor.b1f54f19.js:80799
createElm @ vendor.b1f54f19.js:80760
updateChildren @ vendor.b1f54f19.js:81033
patchVnode @ vendor.b1f54f19.js:81136
updateChildren @ vendor.b1f54f19.js:81010
patchVnode @ vendor.b1f54f19.js:81136
patch @ vendor.b1f54f19.js:81280
Vue._update @ vendor.b1f54f19.js:78953
updateComponent @ vendor.b1f54f19.js:79038
get @ vendor.b1f54f19.js:79424
run @ vendor.b1f54f19.js:79499
flushSchedulerQueue @ vendor.b1f54f19.js:79276
(anonymous) @ vendor.b1f54f19.js:77188
flushCallbacks @ vendor.b1f54f19.js:77114
Promise.then (async)
timerFunc @ vendor.b1f54f19.js:77141
nextTick @ vendor.b1f54f19.js:77198
queueWatcher @ vendor.b1f54f19.js:79352
update @ vendor.b1f54f19.js:79489
notify @ vendor.b1f54f19.js:76003
reactiveSetter @ vendor.b1f54f19.js:76326
(anonymous) @ vendor.b1f54f19.js:195453
(anonymous) @ vendor.b1f54f19.js:195452
updateRoute @ vendor.b1f54f19.js:194885
(anonymous) @ vendor.b1f54f19.js:194748
(anonymous) @ vendor.b1f54f19.js:194870
step @ vendor.b1f54f19.js:194554
runQueue @ vendor.b1f54f19.js:194565
(anonymous) @ vendor.b1f54f19.js:194865
step @ vendor.b1f54f19.js:194554
(anonymous) @ vendor.b1f54f19.js:194558
(anonymous) @ vendor.b1f54f19.js:194850
(anonymous) @ vendor.b1f54f19.js:194632
iterator @ vendor.b1f54f19.js:194831
step @ vendor.b1f54f19.js:194557
step @ vendor.b1f54f19.js:194561
step @ vendor.b1f54f19.js:194561
step @ vendor.b1f54f19.js:194561
(anonymous) @ vendor.b1f54f19.js:194558
(anonymous) @ vendor.b1f54f19.js:194850
beforeGuard @ vendor.b1f54f19.js:145756
iterator @ vendor.b1f54f19.js:194831
step @ vendor.b1f54f19.js:194557
runQueue @ vendor.b1f54f19.js:194565
confirmTransition @ vendor.b1f54f19.js:194858
transitionTo @ vendor.b1f54f19.js:194745
push @ vendor.b1f54f19.js:195170
push @ vendor.b1f54f19.js:195487
handler @ vendor.b1f54f19.js:193851
invokeWithErrorHandling @ vendor.b1f54f19.js:77064
invoker @ vendor.b1f54f19.js:77287
original._wrapper @ vendor.b1f54f19.js:81707
Show 37 more frames
vendor.b1f54f19.js:189610 Uncaught (in promise) Forbidden {type: "FeathersError", name: "Forbidden", message: "Cette opération ne peut être réalisée: non autorisée", code: 403, className: "forbidden", …}

**Comment by cnouguier** [comment]
When we add an image, the following line is called raising the error : https://github.com/kalisio/kdk/blob/master/core/client/components/input/KUploader.vue#L120

**Comment by claustres** [comment]
Linked to https://github.com/kalisio/kdk/issues/204
