### ISSUE TITLE
Highlight when a search filter is enabled

### ISSUE THREAD

**Issue by claustres** [kalisio/aktnmap#159]
If the search bar is not currently displayed the user might not be aware that a filter is active when for instance listing members of a group from the group activity. It would be great if this can be highlighted either in the app bar (e.g. a badge or a different color on the search icon) or the activity itself.

**Comment by cnouguier** [comment]
Closed following https://github.com/kalisio/kdk/commit/6d76d80bee33ffc3a77e840173e0b04bd3881195
