### ISSUE TITLE
Refactor the layout using new KDK capabilities

### ISSUE THREAD

**Issue by cnouguier** [kalisio/aktnmap#218]
Linked to https://github.com/kalisio/kdk/issues/285.

The following tasks are to be done:
* [x] update application configuration
* [x] update activities
* [x] use new layout ability to inject custom components for legend, etc.
* [x] modals
* [x] forms
* [x] update i18n
* [x] update user workflow (detailed below)
* [x] update docs
* [x] update tours
* [x] update tests

Instead of listing all events by organisation on the home page simply display a grid of all organisations with a badge indicating current running events in each one. Add actions to the organisation card acting as shortcuts to the organisation activities like archived events or organisation management. Then provide an event dashboard as a global map.

Some issues to be discussed/fixed:
* unified graphical charter, now we have the top pane in grey while the right panel uses the primary color 
* using back/forward history navigation causes some component not be recreated (eg uploader in events activity)

**Comment by claustres** [comment]
Remaining issues:
* when trigerring some actions in the archived events activity the binded items seems to always be the first one
* using back/forward history navigation causes some component not be be recreated (eg uploader in events activity)
