### ISSUE TITLE
Upgrade to MongoDB v4

### ISSUE THREAD

**Issue by claustres** [kalisio/aktnmap#225]
MongoDB version 3.6 will reach End of Life (EOL) on 30 April, 2021. As we use an Atlas cluster in production, which is currently running MongoDB 3.6, it will be automatically upgraded to MongoDB 4.0 on April 30, 2021. We should test the application against this version and upgrade prior to this EOL date.

**Comment by cnouguier** [comment]
In dev and test mode we successfully tested the app with MongoDB 4.2

**Comment by claustres** [comment]
Tested the live migration to a new v4.2 cluster under Mongo Atlas fine. However, stitch functions are lost on the new cluster and need to be reconfigured.

**Take care that the live migration seems to remove the database user used for the migration at the end of the process, so don't do it with the user used by the application to connect to the cluster.**

**Comment by claustres** [comment]
Production.s been migrated
