### ISSUE TITLE
Logbook : filters + icons/color to give more visibility between closed and open events

### ISSUE THREAD

**Issue by kazemar** [kalisio/aktnmap#291]
To give the user the possibility to show or hide closed or open events we could add a filter to sort them. 

The list could be illustrated by icons or a light background color to show if the events are open or closed like this :
![image](https://user-images.githubusercontent.com/6574960/130753655-0b984f27-eb8e-4a59-bc24-9a33233ba959.png)

**Comment by claustres** [comment]
In the next version there will be a chip indicating the state of the event (closed/open), which should make the job.
Not sure if filtering closed/open events is relevant as the goal of the logbook is to have a complete overview of what is going on.

**Comment by kazemar** [comment]
Yes if it's more visible, I agree we don't need to filter the items of this page
