### ISSUE TITLE
Use a Database as a Service

### ISSUE THREAD

**Issue by claustres** [kalisio/aktnmap#3]
https://www.mongodb.com/cloud/atlas

**Comment by claustres** [comment]
Test a free cluster and it seems to work fine simply by changing the URL to something like `'mongodb://login:password@aktnmap-shard-00-00-odbz7.mongodb.net:27017,aktnmap-shard-00-01-odbz7.mongodb.net:27017,aktnmap-shard-00-02-odbz7.mongodb.net:27017/aktnmap?ssl=true&replicaSet=aktnmap-shard-0&authSource=admin&retryWrites=true'`.

We will need to avoid deploying our own MongoDB container/backup on test and prod environments.

**Comment by claustres** [comment]
Tested also a mongorestore of our current test DB.

**Comment by cnouguier** [comment]
Avoid deploying our own MongoDB container/backup on test and prod environments
- [ ] kApp
- [ ] Akt'n'Map
