### ISSUE TITLE
Option to give group management to new member doesn't work

### ISSUE THREAD

**Issue by kazemar** [kalisio/aktnmap#385]
Action :
I add a new member to an existing group. I use for that the "Join a group" tool, type the group name and activate the "Delegate group management to this member?" toggle.
![image](https://user-images.githubusercontent.com/6574960/175331357-e34d4276-39e3-4c55-a62b-7c66b9ed3024.png)

In the members page, in the group informations popup, the member doesn't seem to be a group manager :
![image](https://user-images.githubusercontent.com/6574960/175331911-d5771193-4238-4311-9eca-cb2eee129790.png)

I disconnect from manager and connect with the member account : I can't add new members :
![image](https://user-images.githubusercontent.com/6574960/175333786-faf7ed6c-b42d-4691-9957-8b831f2703bb.png)

I disconnect from member and connect with the manager account : in the members management page, I give to the member the Manager right to the group :
![image](https://user-images.githubusercontent.com/6574960/175332707-2c536244-bcc2-44cc-ac1c-4dce51473996.png)

I disconnect from manager and connect with the member account : I can now add new members to the group :
![image](https://user-images.githubusercontent.com/6574960/175333519-571e087a-89bb-4720-ae79-073accd5efcd.png)

**Comment by claustres** [comment]
Linked to https://github.com/kalisio/kdk/issues/608.
