### ISSUE TITLE
Replication can make application crash at startup

### ISSUE THREAD

**Issue by claustres** [kalisio/aktnmap#72]
Probably due to concurrent read/write to initialize MongoDB, example error messages:
```
MongoError: a collection 'aktnmap.events' already exists

E11000 duplicate key error collection: aktnmap.catalog index: name_1 dup key: { : "OSM Bright" }
```

Using https://docs.docker.com/engine/swarm/swarm-tutorial/rolling-update/ is probably the way to go

**Comment by cnouguier** [comment]
Seems that rolling-update capabilities are taken into account when updating the service and not when creating the service.
